### ISSUE TITLE
Return to default

### ISSUE THREAD

**Issue by mbailey0523** [huberkyle/Kyle-Aaron-Morgan-GPA-Probation-App#10]
When refreshing the page, the fields do not return to their default value.

**Comment by huberkyle** [comment]
We will have to add a form reset button in the next cycle. I also found out that it depends on the browser. Chrome on Windows resets the form on refresh. Regardless a button would be the best solution.

**Comment by mbailey0523** [comment]
sounds good. I just wanted to make sure it was noted.

**Comment by huberkyle** [comment]
Not in the scope of the current user stories. Reopening the page will clear in Firefox if cache is cleared.
